### ISSUE TITLE
An action could not be found at URI

### ISSUE THREAD

**Issue by finleygn** [xmflsct/action-vercel-deployment#7]
Getting this error message:

`##[error]An action could not be found at the URI 'https://api.github.com/repos/actions/vercel-deployment/tarball/0.5.3'`

through usage

```
      - name: Serverless deploy
        uses: actions/vercel-deployment@0.5.3
        with:
          vercelToken: ${{ secrets.VERCEL_TOKEN }}
          vercelOrgId: xxxxxxx
          vercelProjectId: xxxxxxxxxxxx
          githubToken: ${{ secrets.GITHUB_TOKEN }}
        env:
          SOME_PRIVATE_ENV_VARIABLES: 1
```

tried with `actions/vercel-deployment@0.5.3` & `actions/vercel-deployment@0.5.1`

**Comment by ezalorsara** [comment]
Same I'm also getting that error. Is there any update

**Comment by finleygn** [comment]
@ezalorsara I've migrated to [vercel action](https://github.com/amondnet/vercel-action) for now

**Comment by estebansolo** [comment]
Use this instead

`xmflsct/action-vercel-deployment@v0.5.3`

```
      - name: Serverless deploy
        uses: xmflsct/action-vercel-deployment@v0.5.3
        with:
          vercelToken: ${{ secrets.VERCEL_TOKEN }}
          vercelOrgId: xxxxxxx
          vercelProjectId: xxxxxxxxxxxx
          githubToken: ${{ secrets.GITHUB_TOKEN }}
        env:
          SOME_PRIVATE_ENV_VARIABLES: 1
```
